"""empty message

Revision ID: 0f1a230793fe
Revises: be989d288eeb
Create Date: 2026-06-25 19:02:54.630802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1a230793fe'
down_revision: Union[str, Sequence[str], None] = 'be989d288eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('pending_ref_bonus', sa.Integer(), server_default='0', nullable=False),
    sa.Column('earned_coins', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('refferals')
    op.add_column('users', sa.Column('last_passive_calculation', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_passive_calculation')
    op.create_table('refferals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referred_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('earned_coins', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.Column('pending_ref_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], name=op.f('refferals_referred_id_fkey')),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('refferals_referrer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refferals_pkey'))
    )
    op.drop_table('referals')
    # ### end Alembic commands ###
