"""empty message

Revision ID: 4da1a2f8927a
Revises: 60cebd97c0be
Create Date: 2026-07-05 14:59:51.607880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da1a2f8927a'
down_revision: Union[str, Sequence[str], None] = '60cebd97c0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('desc', sa.String(), server_default='desc', nullable=False))
    op.drop_column('quests', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('quests', 'desc')
    # ### end Alembic commands ###
