"""Referrals table name fix

Revision ID: 60cebd97c0be
Revises: 7d0882d474c8
Create Date: 2026-07-01 09:11:05.326582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cebd97c0be'
down_revision: Union[str, Sequence[str], None] = '7d0882d474c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('pending_ref_bonus', sa.Integer(), server_default='0', nullable=False),
    sa.Column('earned_coins', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('referals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referred_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pending_ref_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('earned_coins', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], name='referals_referred_id_fkey'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name='referals_referrer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='referals_pkey')
    )
    op.drop_table('referrals')
    # ### end Alembic commands ###
