"""initial schema

Revision ID: 8c67c88876e2
Revises: 
Create Date: 2026-09-27 11:28:37.428774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c67c88876e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leadmagnets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), server_default='Location', nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('bonus_multiplier', sa.Float(), nullable=False),
    sa.Column('color', sa.String(), server_default='#b6a0ff', nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default='name', nullable=False),
    sa.Column('desc', sa.String(), server_default='desc', nullable=False),
    sa.Column('base_reward', sa.Integer(), nullable=False),
    sa.Column('reward_multiplier', sa.Float(), server_default='1.5', nullable=False),
    sa.Column('base_goal', sa.Integer(), nullable=False),
    sa.Column('goal_multiplier', sa.Float(), server_default='2.0', nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upgrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), server_default='click', nullable=False),
    sa.Column('unlock_lvl', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('icon_name', sa.String(), server_default='Gamepad2', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('coins', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('total_taps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('energy', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('max_energy', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('last_passive_calculation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_energy_calculation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_click_at', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('deposit_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bonus_claimed', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=False)
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leadmagnet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leadmagnet_id'], ['leadmagnets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('pending_ref_bonus', sa.Integer(), server_default='0', nullable=False),
    sa.Column('earned_coins', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completions', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_upgrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upgrade_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['upgrade_id'], ['upgrades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_upgrades')
    op.drop_table('user_quests')
    op.drop_table('user_locations')
    op.drop_table('referrals')
    op.drop_table('followers')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_table('users')
    op.drop_table('upgrades')
    op.drop_table('quests')
    op.drop_table('locations')
    op.drop_table('leadmagnets')
    # ### end Alembic commands ###
