"""empty message

Revision ID: e19836c1d63e
Revises: c3f0d73517fa
Create Date: 2026-06-27 16:32:41.047196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19836c1d63e'
down_revision: Union[str, Sequence[str], None] = 'c3f0d73517fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_energy_calculation', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('users', 'last_click')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_click', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_energy_calculation')
    # ### end Alembic commands ###
