"""empty message

Revision ID: ef9c2ed193bc
Revises: 8ede10573dd3
Create Date: 2026-06-03 22:07:29.166067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9c2ed193bc'
down_revision: Union[str, Sequence[str], None] = '8ede10573dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_deposit', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_deposit_reset', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_deposit_reset')
    op.drop_column('users', 'daily_deposit')
    # ### end Alembic commands ###
